[package]
name = "rsa-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsa"
path = "source/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.57"
clap = { version = "4.4.6", features = ["derive"] }
